Trying:
    BaseGeometry = __import__('7-base_geometry').BaseGeometry
Expecting nothing
ok
Trying:
    bg = BaseGeometry()
Expecting nothing
ok
Trying:
    print(bg.area())
Expecting:
    Traceback (most recent call last):
    Exception: area() is not implemented
ok
Trying:
    print(bg.integer_validator) # doctest: +ELLIPSIS, +NORMALIZE_WHITESPACE
Expecting:
        <bound method BaseGeometry.integer_validator of <7-base_geometry.BaseGeometry 
        object at...>>
ok
Trying:
    bg.integer_validator("name", "5")
Expecting:
    Traceback (most recent call last):
    TypeError: name must be an integer
ok
Trying:
    bg.integer_validator("width", -5)
Expecting:
    Traceback (most recent call last):
    ValueError: width must be greater than 0
ok
Trying:
    bg.integer_validator("invalid number", "number")
Expecting:
    Traceback (most recent call last):
    TypeError: invalid number must be an integer
ok
Trying:
    bg = BaseGeometry()
Expecting nothing
ok
Trying:
    bg.integer_validator("age", 5)
Expecting nothing
ok
Trying:
    bg = BaseGeometry()
Expecting nothing
ok
Trying:
    bg.integer_validator("name", [1,2,3])
Expecting:
    Traceback (most recent call last):
    TypeError: name must be an integer
ok
Trying:
    bg = BaseGeometry()
Expecting nothing
ok
Trying:
    bg.integer_validator("name", (1,2))
Expecting:
    Traceback (most recent call last):
    TypeError: name must be an integer
ok
Trying:
    bg = BaseGeometry()
Expecting nothing
ok
Trying:
    bg.integer_validator("name", {1, 2})
Expecting:
    Traceback (most recent call last):
    TypeError: name must be an integer
ok
Trying:
    bg = BaseGeometry()
Expecting nothing
ok
Trying:
    bg.integer_validator("name", None)
Expecting:
    Traceback (most recent call last):
    TypeError: name must be an integer
ok
Trying:
    bg.integer_validator("distance", -4)
Expecting nothing
**********************************************************************
File "./tests/7-base_geometry.txt", line 59, in 7-base_geometry.txt
Failed example:
    bg.integer_validator("distance", -4)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.12/doctest.py", line 1361, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 7-base_geometry.txt[17]>", line 1, in <module>
        bg.integer_validator("distance", -4)
      File "/home/phantomwatchdog/holbertonschool-higher_level_programming/python-inheritance/7-base_geometry.py", line 26, in integer_validator
        raise ValueError("{} must be greater than 0".format(name))
    ValueError: distance must be greater than 0
**********************************************************************
1 items had failures:
   1 of  18 in 7-base_geometry.txt
18 tests in 1 items.
17 passed and 1 failed.
***Test Failed*** 1 failures.
